### ISSUE TITLE
modal is too big in mobile screen

### ISSUE THREAD

**Issue by thecodermehedi** [thecodermehedi/phonehunter#2]
### ⚙️ Title:

Modal is too big in mobile screen

### ℹ️ Description

 Open this Live [Website](https://dub.sh/phonehunter) in mobile view, click any of the phones or search for phones , click on show details button you will see that modal's is too big in mobile screen some parts are cut off.

### Expected Behavior

Modal should be small and readable in mobile screen 

### 📘 Contribution Guidelines

Please make sure to read our [Contribution Guidelines](https://github.com/devbytemehedi/phonehunter/blob/main/CONTRIBUTION.md) before submitting your contribution.

🤔 If you have any questions or need further assistance, feel free to ask on this issue.

Thank you for contributing!
---

### 💡 Tips

- Keep your changes focused and small.
- If you need help, don't hesitate to ask questions in the comments.

**Comment by devbytemehedi** [comment]
# Fork this 👉 [branch](https://github.com/devbytemehedi/phonehunter/tree/2-modal-is-too-big-in-mobile-screen) to work on this 👉 [issue #2](https://github.com/devbytemehedi/phonehunter/issues/2)

**Comment by devbytemehedi** [comment]
@bilalmirza74 create pull request agian in this [2-modal-is-too-big-in-mobile-screen](https://github.com/devbytemehedi/phonehunter/tree/2-modal-is-too-big-in-mobile-screen) branch not in main.

**Comment by devbytemehedi** [comment]
@bilalmirza74 it will look something like this
![pull-ss](https://github.com/devbytemehedi/phonehunter/assets/89072438/9ef2204d-536a-4a96-8f84-f31c1dd00644)
